### ISSUE TITLE
IO2-04 Nieprawidłowa numeracja podkroków

### ISSUE THREAD

**Issue by TangerEye** [xplolel/ioioio#17]
![obraz](https://user-images.githubusercontent.com/10261296/49767658-af108b80-fcd9-11e8-8418-2f186fa5d3fd.png)

Dla tego przypadku powinno być 2.2.1 dla kroku drugiego od dołu. Sprawdzić jak są przypisywane numery dla głębokości >2

**Comment by krasnoludkolo** [comment]
Powinno być 2.1.1.
